### ISSUE TITLE
'isnan' was not declared in this scope

### ISSUE THREAD

**Issue by oije2333** [benjamin-bader/cppmetrics#8]
Re: Git tag v0.1.1: Receiving this error using g++-5 through g++-7 on Ubuntu 18.04.2.

File is WeightedSnapshot.cc.

Since C++11, "isnan" is declared within the "std" namespace. Thus, for portability the the function must be properly qualified as "std::isnan". That will fix the problem.

Notice this was fixed 10 Apr 2018. Could a git tag be created for a version that includes the change?

**Comment by benjamin-bader** [comment]
Done!  Just pushed a tag named v0.1.2.
